# Generated by Django 3.1.7 on 2021-03-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.FileField(upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
